version: '3.8'

services:
  backend:
    build: ./backend
    network_mode: host
    volumes:
      - ~/.kube:/root/.kube:ro
      - ~/.minikube:/home/muhammadusama/.minikube:ro
    environment:
      - MOCK_MODE=false
      - HOME=/root

  frontend:
    build: ./frontend
    ports:
      - "80:80"
    depends_on:
      - backend

  agent:
    build: ./agent
    image: shieldkube-agent:latest
    network_mode: host
    profiles: ["tools"]
    environment:
      - SHIELDKUBE_URL=http://localhost:8000
      - CLUSTER_ID=local-agent-test
      - SHIELDKUBE_API_KEY=shieldkube-default-key-2024

  backend-go:
    build: ./backend-go
    container_name: shieldkube-go-engine
    network_mode: host
    environment:
      - SHIELDKUBE_URL=http://localhost:8000
      - CLUSTER_ID=local-go-deep-scan
