apiVersion: v1
kind: Namespace
metadata:
  name: shieldkube-go
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: shieldkube-go-sa
  namespace: shieldkube-go
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: shieldkube-go-role
rules:
- apiGroups: ["", "apps", "networking.k8s.io", "rbac.authorization.k8s.io", "policy", "metrics.k8s.io"]
  resources: ["pods", "nodes", "services", "configmaps", "secrets", "namespaces", "events", "deployments", "replicasets", "networkpolicies", "clusterroles", "resourcequotas", "limitranges", "poddisruptionbudgets"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: shieldkube-go-binding
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: shieldkube-go-role
subjects:
- kind: ServiceAccount
  name: shieldkube-go-sa
  namespace: shieldkube-go
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: shieldkube-go-agent
  namespace: shieldkube-go
spec:
  replicas: 1
  selector:
    matchLabels:
      app: shieldkube-go-agent
  template:
    metadata:
      labels:
        app: shieldkube-go-agent
    spec:
      serviceAccountName: shieldkube-go-sa
      hostPID: true
      containers:
      - name: go-agent
        image: muhammadusama9/shieldkube-go:latest
        imagePullPolicy: Always
        env:
        - name: SHIELDKUBE_URL
          value: "http://shieldkube-backend.default.svc.cluster.local:8000"
        - name: CLUSTER_ID
          value: "remote-go-cluster"
        - name: CLUSTER_NAME
          value: "High-Performance Go Cluster"
        - name: SYNC_INTERVAL_SEC
          value: "60"
        resources:
          limits:
            cpu: "500m"
            memory: "512Mi"
          requests:
            cpu: "100m"
            memory: "256Mi"
        volumeMounts:
        # Host mounts required for kube-bench to analyze node configuration
        - name: etc-kubernetes
          mountPath: /etc/kubernetes
          readOnly: true
        - name: var-lib-etcd
          mountPath: /var/lib/etcd
          readOnly: true
      volumes:
      - name: etc-kubernetes
        hostPath:
          path: /etc/kubernetes
      - name: var-lib-etcd
        hostPath:
          path: /var/lib/etcd
